# Generated by Django 5.1.1 on 2024-09-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employers_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
