# Generated by Django 5.1.1 on 2024-09-06 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employers_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employers',
            name='reg_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
