# Generated by Django 5.1.1 on 2024-09-06 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employers_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employers',
            name='reg_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
