# Generated by Django 5.1.1 on 2024-09-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=255)),
                ('contact_info', models.EmailField(max_length=255)),
                ('equipment_type', models.CharField(max_length=255)),
                ('urgency', models.CharField(max_length=10)),
                ('justification', models.TextField()),
            ],
        ),
    ]
