# Generated by Django 5.1.1 on 2024-09-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentRequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
