# Generated by Django 5.0.7 on 2024-09-07 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0005_alter_employers_reg_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('purchase_date', models.DateField(default=django.utils.timezone.now)),
                ('date_of_receipt', models.DateField(default=django.utils.timezone.now)),
                ('warranty_expiration_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=100)),
                ('equipment_type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_form', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='employers.employers')),
            ],
        ),
    ]
