# Generated by Django 5.0.7 on 2024-09-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='departament',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
