# Generated by Django 5.1.1 on 2024-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_equipment_departament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='departament',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
