# Generated by Django 5.1.1 on 2024-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelTag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeltag',
            name='prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
